using EchoOfTheTimes.SceneManagement;
using EchoOfTheTimes.ScriptableObjects;
using EchoOfTheTimes.ScriptableObjects.Persistence;
using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using Zenject;

namespace EchoOfTheTimes.Persistence
{
    public class PersistenceService : MonoBehaviour
    {
        public static Action<int> OnLevelCompleted { get; private set; }
        public static Action OnExitToMainMenu { get; private set; }

        private SaveLoadService _saveLoadService;
        public string LastLoadedLevel { get; private set; }
        private PresetType _presetType;
        private PlayerData _defaultData;
        private PlayerData _allUnlockData;

        private void OnDestroy()
        {
            OnLevelCompleted -= HandleLevelCompleted;
            OnExitToMainMenu -= HandleExitToMainMenu;
        }

        [Inject]
        private void Construct()
        {
            OnLevelCompleted += HandleLevelCompleted;
            OnExitToMainMenu += HandleExitToMainMenu;
            LoadPresets();

            _presetType = (Resources.Load(@"ScriptableObjects/BootstrapSettings") as BootstrapSettingsScriptableObject).UsedSavingPreset;

            _saveLoadService = _presetType switch
            {
                PresetType.SavedFile => new SaveLoadService(_defaultData),
                PresetType.Default => new SaveLoadService(_defaultData, true),
                PresetType.AllUnlock => new SaveLoadService(_allUnlockData, true),
                _ => throw new NotImplementedException($"Not implemented {nameof(PresetType)} with value: '{_presetType}'!"),
            };

            Debug.Log($"Enable {_saveLoadService} with preset: {_presetType}!");
        }

        private void LoadPresets()
        {
            _defaultData = LoadPresetFromResources(@"ScriptableObjects/Persistence/PlayerDataDefaultPreset-AutoGenerated");
            _allUnlockData = LoadPresetFromResources(@"ScriptableObjects/Persistence/PlayerDataUnlockedAllPreset-AutoGenerated");
        }

        private PlayerData LoadPresetFromResources(string path)
        {
            var preset = Resources.LoadAsync(path).asset as PlayerDataPresetScriptableObject;
            if (preset == null)
            {
                throw new NullReferenceException($"You need to create '{path.Split(Path.PathSeparator)[^1]}' first!");
            }
            return preset.Data;
        }

        private void HandleLevelCompleted(int collected)
        {
            var newDataToSave = _saveLoadService.DataToSave;
            if (string.IsNullOrEmpty(LastLoadedLevel))
            {
                LastLoadedLevel = newDataToSave.Data[1].Levels[0].FullName;
            }

            // ќтмечаем текущий уровень как завершЄнный (без работы с коллектаблами)
            newDataToSave = MarkThisLevelAsCompleted(newDataToSave, collected, out int lastLoadedChapterIndex, out int lastLoadedLevelIndex);
            bool isLastLevelInChapter = lastLoadedLevelIndex == newDataToSave.Data[lastLoadedChapterIndex].Levels.Count - 1;

            if (!isLastLevelInChapter)
            {
                UnlockNextLevelIfLocked(newDataToSave, lastLoadedChapterIndex, lastLoadedLevelIndex + 1);
                LastLoadedLevel = newDataToSave.Data[lastLoadedChapterIndex].Levels[lastLoadedLevelIndex + 1].FullName;
            }
            else
            {
                newDataToSave.Data[lastLoadedChapterIndex].ChapterStatus = StatusType.Completed;
                if (lastLoadedChapterIndex < newDataToSave.Data.Count - 1)
                {
                    UnlockNextChapter(newDataToSave, lastLoadedChapterIndex + 1);
                    LastLoadedLevel = newDataToSave.Data[lastLoadedChapterIndex + 1].Levels[0].FullName;
                }
                else
                {
                    LastLoadedLevel = newDataToSave.Data[lastLoadedChapterIndex].Levels[0].FullName;
                }
            }

            newDataToSave.LastLoadedLevelFullName = LastLoadedLevel;
            _saveLoadService.DataToSave = newDataToSave;
            if (_presetType == PresetType.SavedFile)
            {
                _saveLoadService.Save();
            }
        }

        private void UnlockNextChapter(PlayerData data, int nextChapterIndex)
        {
            if (nextChapterIndex < data.Data.Count)
            {
                data.Data[nextChapterIndex].ChapterStatus = StatusType.Unlocked;
                if (data.Data[nextChapterIndex].Levels.Count > 0)
                {
                    data.Data[nextChapterIndex].Levels[0].LevelStatus = StatusType.Unlocked;
                }
            }
        }

        private void UnlockNextLevelIfLocked(PlayerData data, int chapterIndex, int levelIndex)
        {
            if (levelIndex < data.Data[chapterIndex].Levels.Count &&
                data.Data[chapterIndex].Levels[levelIndex].LevelStatus == StatusType.Locked)
            {
                data.Data[chapterIndex].Levels[levelIndex].LevelStatus = StatusType.Unlocked;
            }
        }

        private string GetNextLevelInCurrentChapter(PlayerData newDataToSave, int chapterIndex, int levelIndex)
        {
            if (levelIndex < newDataToSave.Data[chapterIndex].Levels.Count - 1)
            {
                return newDataToSave.Data[chapterIndex].Levels[levelIndex + 1].FullName;
            }
            else if (chapterIndex < newDataToSave.Data.Count - 1)
            {
                return newDataToSave.Data[chapterIndex + 1].Levels[0].FullName;
            }
            else
            {
                return newDataToSave.Data[chapterIndex].Levels[levelIndex].FullName;
            }
        }

        private StatusType GetCurrentLevelStatus(PlayerData data)
        {
            var chapterIndex = data.Data.FindIndex(ch => ch.Title == LastLoadedLevel.Split('|')[0]);
            var levelIndex = data.Data[chapterIndex].Levels.FindIndex(lvl => lvl.LevelName == LastLoadedLevel.Split('|')[1]);
            return data.Data[chapterIndex].Levels[levelIndex].LevelStatus;
        }

        // ћетод проверки коллектаблов больше не используетс€ Ц оставл€ем заглушку.
        public bool CheckAllCollectablesCollected(GameChapter chapter)
        {
            return true;
        }

        public List<GameChapter> GetData() => _saveLoadService.DataToSave.Data;

        public bool GetSettings() => _saveLoadService.DataToSave.SoundsMuted;

        public void SetAndSaveSetttings(bool isMuted)
        {
            _saveLoadService.DataToSave.SoundsMuted = isMuted;
            if (_presetType == PresetType.SavedFile)
            {
                _saveLoadService.Save();
            }
        }

        public void UpdateLastLoadedLevel(GameLevel level) => LastLoadedLevel = level.FullName;

        public GameLevel GetLevel(string chapterTitle, string levelName)
        {
            var chapterIndex = _saveLoadService.DataToSave.Data.FindIndex(chapter => chapter.Title == chapterTitle);
            var levelIndex = _saveLoadService.DataToSave.Data[chapterIndex].Levels.FindIndex(
                level => level.LevelName == levelName);
            return _saveLoadService.DataToSave.Data[chapterIndex].Levels[levelIndex];
        }

        private PlayerData MarkThisLevelAsCompleted(PlayerData newDataToSave, int collected,
            out int lastLoadedChapterIndex, out int lastLoadedLevelIndex)
        {
            var lastLoadedChapterTitle = LastLoadedLevel.Split('|')[0];
            var lastLoadedLevelName = LastLoadedLevel.Split('|')[1];
            lastLoadedChapterIndex = -1;
            lastLoadedLevelIndex = -1;
            for (int i = 0; i < newDataToSave.Data.Count; i++)
            {
                if (newDataToSave.Data[i].Title == lastLoadedChapterTitle)
                {
                    var lastLoadedChapter = newDataToSave.Data[i];
                    lastLoadedChapterIndex = i;
                    for (int j = 0; j < lastLoadedChapter.Levels.Count; j++)
                    {
                        if (lastLoadedChapter.Levels[j].LevelName == lastLoadedLevelName)
                        {
                            lastLoadedChapter.Levels[j].LevelStatus = StatusType.Completed;
                            // ”бираем присвоение значени€ дл€ коллектаблов
                            lastLoadedLevelIndex = j;
                            break;
                        }
                    }
                    break;
                }
            }
            return newDataToSave;
        }

        private void HandleExitToMainMenu()
        {
            if (_presetType == PresetType.SavedFile)
            {
                _saveLoadService.Save();
            }
        }
    }
}
